on:
   schedule:
   - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Generate
        run: |
          printenv SERVICE_ACCOUNT_JSON > "$GOOGLE_APPLICATION_CREDENTIALS"
          python -m pip install -r requirements.txt
          python main.py
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Updates for `date`"
          git push
